"""Stage 5 - render a standalone HTML audit report (inbox_audit.html)."""
import html
import json
from pathlib import Path

_CSS = """
body{font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;
 margin:0;background:#f4f6f8;color:#1d2733}
header{background:#1f3a5f;color:#fff;padding:20px 32px}
header h1{margin:0;font-size:22px}
header p{margin:4px 0 0;opacity:.8;font-size:13px}
main{max-width:1100px;margin:24px auto;padding:0 20px}
.cards{display:flex;flex-wrap:wrap;gap:12px;margin-bottom:24px}
.card{background:#fff;border:1px solid #dde3ea;border-radius:8px;
 padding:14px 18px;min-width:150px;flex:1}
.card .num{font-size:24px;font-weight:700;color:#1f3a5f}
.card .lbl{font-size:12px;color:#5b6b7c;text-transform:uppercase;
 letter-spacing:.05em}
section{background:#fff;border:1px solid #dde3ea;border-radius:8px;
 padding:18px 22px;margin-bottom:20px}
h2{margin-top:0;font-size:17px;color:#1f3a5f}
table{width:100%;border-collapse:collapse;font-size:13px}
th,td{text-align:left;padding:7px 10px;border-bottom:1px solid #e6ebf0;
 vertical-align:top}
th{background:#eef2f6;font-size:12px;text-transform:uppercase;
 letter-spacing:.04em;color:#41556b}
tr:last-child td{border-bottom:none}
.badge{display:inline-block;padding:2px 8px;border-radius:10px;font-size:11px;
 font-weight:600;background:#e6ebf0}
.badge.unsubscribe_and_purge{background:#fde2e2;color:#a02222}
.badge.unsubscribe{background:#fff3d6;color:#8a6200}
.badge.review_delete{background:#ffe9d6;color:#964d00}
.badge.review{background:#e4ecfb;color:#2b4d8f}
.badge.archive{background:#e8e8f6;color:#4a4a8f}
.badge.keep{background:#ddf3e4;color:#1e6b3a}
footer{text-align:center;color:#8a97a5;font-size:12px;padding:20px}
"""


def _e(value) -> str:
    return html.escape(str(value if value is not None else ""))


def _card(num, label) -> str:
    return f'<div class="card"><div class="num">{_e(num)}</div><div class="lbl">{_e(label)}</div></div>'


def run(summary_path: Path, worklist_path: Path, out_path: Path, log=print) -> Path:
    summary = json.loads(summary_path.read_text(encoding="utf-8"))
    worklist = json.loads(worklist_path.read_text(encoding="utf-8"))

    date_range = summary.get("date_range") or {}
    cards = "".join(
        [
            _card(summary.get("total_messages", 0), "Messages"),
            _card(summary.get("unique_senders", 0), "Sender groups"),
            _card(summary.get("unique_domains", 0), "Domains"),
            _card(f"{summary.get('total_size_bytes', 0):,}", "Total bytes"),
            _card(summary.get("senders_with_unsubscribe", 0), "Unsubscribe-ready"),
        ]
    )

    top_rows = "".join(
        f"<tr><td>{i}</td><td>{_e(s['sender'])}</td>"
        f"<td>{s['messages']}</td><td>{s['size_bytes']:,}</td></tr>"
        for i, s in enumerate(summary.get("top_senders", []), start=1)
    )

    wl_rows = "".join(
        "<tr>"
        f"<td>{_e(it['sender_group'])}</td>"
        f'<td><span class="badge {_e(it["recommended_action"])}">'
        f"{_e(it['recommended_action'])}</span></td>"
        f"<td>{it['message_count']}</td>"
        f"<td>{it['total_size_bytes']:,}</td>"
        f"<td>{'yes' if it['has_unsubscribe'] else 'no'}</td>"
        f"<td>{_e(it['reason'])}</td>"
        "</tr>"
        for it in worklist.get("items", [])
    )

    page = f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Inbox Audit - email-doctor</title>
<style>{_CSS}</style>
</head>
<body>
<header>
<h1>Inbox Audit Report</h1>
<p>Generated {_e(summary.get('generated_at', ''))} &middot;
{_e((date_range.get('first') or '')[:10])} &rarr; {_e((date_range.get('last') or '')[:10])}</p>
</header>
<main>
<div class="cards">{cards}</div>
<section>
<h2>Top senders</h2>
<table><thead><tr><th>#</th><th>Sender</th><th>Messages</th><th>Bytes</th></tr></thead>
<tbody>{top_rows}</tbody></table>
</section>
<section>
<h2>Cleanup worklist</h2>
<table><thead><tr><th>Sender</th><th>Action</th><th>Messages</th><th>Bytes</th>
<th>Unsub</th><th>Reason</th></tr></thead>
<tbody>{wl_rows}</tbody></table>
</section>
</main>
<footer>Generated by email-doctor</footer>
</body>
</html>
"""
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(page, encoding="utf-8")
    log(f"HTML report written: {out_path.name}")
    return out_path
